project:
  type: website
  output-dir: docs

website:
  title: "Intermediate Research Methods and Statistics"
  favicon: p_values.jpg
  
  page-footer:
    left: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
    right: |
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/usman-afzali/PSYC344)</span>
    background: "#559BED"
  
  search:
    location: navbar
    type: textbox
  navbar:
    pinned: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: intro.qmd
      - text: "How to Use?"
        file: how-to-use.qmd
      - text: "Labs"
        file: labs.qmd
      - text: "Presentations"
        file: presentations.qmd
      - text: "Course Outline"
        file: outline.qmd
    right:
      - icon: github
        href: https://github.com/usman-afzali/psyc344

    page-navigation: true

format:
  html:
    theme: materia
    css: styles.scss
    highlight-style: espresso
    code-tools: false
    code-block-bg: true
    citations-hover: true

editor: source
