project:
  type: website
  output-dir: docs

website:
  title: "PSYC344"
  favicon: p_values.jpg
  
  page-footer:
    center: |
      <span class="container"><strong>[Contact Usman Afzali](mailto:usman.afzali@canterbury.ac.nz){target="_blank"}</strong></span>
    left: |
      <span class="container"><strong>Made with [Posit Quarto on RStudio](https://quarto.org/){target="_blank"}</strong></span>
    right: |
      <span class="container"><strong>[Github Repo](https://github.com/usman-afzali/PSYC344){target="_blank"}</strong></span>
    background: "#FFA500"
  
  search: 
    location: navbar
    type: textbox
  navbar:
    pinned: true
    left:
      - text: "Welcome"
        file: intro.qmd
      - text: "Labs"
        file: labs.qmd
      - text: "Presentations"
        file: presentations.qmd
    right:
      - icon: github
        href: https://github.com/usman-afzali/PSYC344
    page-navigation: true

format:
  html:
    theme: litera
    css: styles.scss
    highlight-style: espresso
    code-tools: true
    code-block-bg: true
    citations-hover: true

editor: source
