---
title: "Introduction"
listing:
  id: intro-listings
  image-align: right
  contents: intro
  sort: "title asc"
  type: default
  categories: false
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: false
---

Kia ora!

Welcome to PSYC344. 

I am Usman Afzali, the course coordinator and lecturer of the course. I built this website during Jan, 2023 and will keep maintaining it in the future.

This website contains `R` code for `statistics labs` of the Year 3 [Intermediate Research Methods and Statistics](https://www.canterbury.ac.nz/courseinfo/GetCourseDetails.aspx?course=PSYC344&occurrence=22S2(C)&year=2022) course taught at the [School of Psychology, Speech and Hearing, University of Canterbury](https://www.canterbury.ac.nz/science/schools/psyc-speech-hear/). The code is specific to the 2022 Summer course (2022-2023), but is very similar to the previous and *hopefully* future occurrences of the course.

In addition to  `statistics labs`, some weekly `introduction slides` and the `Course Outline` are available too.

For the next course occurrence (July, 2023), weekly lecture slides will be made available too.

::: {.callout-note}

## GitHub Repo

Please access the [PSYC344 Github Repository](https://github.com/usman-afzali/PSYC344) to use or replicate the code for this website. You can also access the `quarto` or `.qmd` files from the repository.

:::

::: callout-tip
## Note

-   Feel free to use/replicate the code.

-   Suggestions welcome.
:::

Kind regards.

Usman Afzali, PhD

[www.usmanafzali.com](https://www.usmanafzali.com)

------------------------------------------------------------------------
